### ISSUE TITLE
Run failed

### ISSUE THREAD

**Issue by mamba-2021** [The-Viper-One/PsMapExec#11]
Great tool
But I have a problem. When this tool is running locally, it appears blank. Could you please help me take a look
Is there a problem with my system, or is it because some features of the tool have been commented out, or something
![image](https://github.com/The-Viper-One/PsMapExec/assets/75511051/66266a15-bcdb-4d99-acf0-2ffcb9c25253)
Thank you.

**Comment by The-Viper-One** [comment]
Hi @mamba-2021.


When running this locally, you should load the script into memory using "dot sourcing." This involves loading it into the current scope with the following command:

```
. .\PsMapExec.ps1
```

You can then freely run commands such as 
```
PsMapExec -help
```

![image](https://github.com/The-Viper-One/PsMapExec/assets/68926315/9eaa53f6-6a13-4408-a814-59c7e1c9ae6e)

A second and generally preffered option is to load directly into memory from Github

```
IEX(New-Object System.Net.WebClient).DownloadString("https://raw.githubusercontent.com/The-Viper-One/PsMapExec/main/PsMapExec.ps1")
```
Then check if loaded correctly.
```
PsMapExec -help
```
![image](https://github.com/The-Viper-One/PsMapExec/assets/68926315/4bbf7a47-7d2b-4894-bcc1-4c01ac731d45)

I hope this helps!

**Comment by mamba-2021** [comment]
![image](https://github.com/The-Viper-One/PsMapExec/assets/75511051/b7b836e9-a652-4b50-8c35-c75a26d692fd)
I used the first method you recommended, and now it's ready. Thank you very much, big shot. I wish you a happy life
