### ISSUE TITLE
Incorrect Username and Password Error

### ISSUE THREAD

**Issue by raghavmishra** [The-Viper-One/PsMapExec#4]
Running into an issue when I provide Username and password from commandline. It uses local auth even though the creds are provided using commandline.
`PsMapExec -Method SMB -Username <user> -Password <pass> -Domain avengershq.local -Targets All`
Since, it is taking local creds that's the reason I am getting invalid auth error. Please have a look at traces screenshot. Also, my computer is not part of the domain.
![invalid](https://github.com/The-Viper-One/PsMapExec/assets/3175190/6e160163-140e-4cc3-9455-a4a443382d4f)

**Comment by The-Viper-One** [comment]
@raghavmishra please try the latest commint in the main branch. This should now (hopefully) address the issue.

**Comment by raghavmishra** [comment]
Sure, I will try it.

**Comment by raghavmishra** [comment]
It is working. Thank you.
